### ISSUE TITLE
Add two new artist images to artist set

### ISSUE THREAD

**Issue by Nikomus** [wearedarts/pairs#33]
[fwdyinkageorgia.zip](https://github.com/wearedarts/pairs/files/7601791/fwdyinkageorgia.zip)

**Comment by katjam** [comment]
@Nikomus Those new svgs render a different size to the others. Did you do some editing of the old ones?

Also I think we decided to go with the full name on badges so if you did process the others we need the full named ones done too.

**Comment by katjam** [comment]
I can't find the svgs with full name badges for the other artists. I think they showed them to us... but we don't have them in the games repo nor trello.

**Comment by Nikomus** [comment]
@katjam I think we said we'd make them as they're just a text edit, but they're completely unreadable with two rows on a name badge.

By default I run SVGs through [SVGO](https://www.npmjs.com/package/svgo) but I tend to use the GUI at https://jakearchibald.github.io/svgomg/ to check the output - depending on scales of the image the precision value can break things if it's too low. That wasn't an issue here though, the pictures were just in a larger canvas. I've edited and pushed them to this branch.
